// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeWwsckk03XXNWz_846efgNHJXNhYjn2s',
    appId: '1:891787785661:web:aeaa9060b2e4451f5bced4',
    messagingSenderId: '891787785661',
    projectId: 'doclabpharm',
    authDomain: 'doclabpharm.firebaseapp.com',
    storageBucket: 'doclabpharm.firebasestorage.app',
    measurementId: 'G-Z28WS3F13V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcUzDErYUDlN13pb1fuIyG-EgCTkVDHGo',
    appId: '1:891787785661:android:1749908f4bcb1dd45bced4',
    messagingSenderId: '891787785661',
    projectId: 'doclabpharm',
    storageBucket: 'doclabpharm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA35sR_GUcsLATCh4t2jlfCF4M6Uh6NgFs',
    appId: '1:891787785661:ios:75b5a22eff78bda35bced4',
    messagingSenderId: '891787785661',
    projectId: 'doclabpharm',
    storageBucket: 'doclabpharm.firebasestorage.app',
    iosBundleId: 'com.doclabpharm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA35sR_GUcsLATCh4t2jlfCF4M6Uh6NgFs',
    appId: '1:891787785661:ios:2fec5484e80384f85bced4',
    messagingSenderId: '891787785661',
    projectId: 'doclabpharm',
    storageBucket: 'doclabpharm.firebasestorage.app',
    iosBundleId: 'com.example.myDocLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeWwsckk03XXNWz_846efgNHJXNhYjn2s',
    appId: '1:891787785661:web:ce0ca88302c9f78a5bced4',
    messagingSenderId: '891787785661',
    projectId: 'doclabpharm',
    authDomain: 'doclabpharm.firebaseapp.com',
    storageBucket: 'doclabpharm.firebasestorage.app',
    measurementId: 'G-4CVETN8LHW',
  );
}
